**Import Libraries**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.statespace.sarimax import SARIMAX
from prophet import Prophet
from statsmodels.tsa.holtwinters import ExponentialSmoothing
import itertools
import pickle

import warnings
warnings.filterwarnings("ignore")

c:\Users\akann\OneDrive\Desktop\AMDARI\Project 4 - Consumer Electronics Sales Forecasting\ElectroTech Sales Forecasting\ElectroTech-Forecasting-Data\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

**Data Importation**

In [2]:
original_data = pd.read_csv(r"C:\Users\akann\OneDrive\Desktop\AMDARI\Project 4 - Consumer Electronics Sales Forecasting\ElectroTech Sales Forecasting\ElectroTech Forecasting Data.csv")
original_data.head(3)

,Product_ID,Category,Price,Date,Season,Market_Trend_Index,Competitor_Activity_Score,Consumer_Confidence_Index,Product_Specification_1,Product_Specification_2,Sales_Volume
0,1103,Laptop,105.32,2009-01-01,Winter,-1.859160,0.546694,84.680465,Spec_C,Long-Battery-Life,49
1,1436,Tablet,145.55,2009-01-01,Winter,-0.345587,0.940428,42.919288,Spec_C,Lightweight,69
2,1271,Smartphone,97.82,2009-01-01,Winter,-0.384738,0.751155,55.191268,Spec_B,Lightweight,50

In [3]:
original_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136193 entries, 0 to 136192
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Product_ID                 136193 non-null  int64
 1   Category                   136193 non-null  object
 2   Price                      136193 non-null  float64
 3   Date                       136193 non-null  object
 4   Season                     136193 non-null  object
 5   Market_Trend_Index         136193 non-null  float64
 6   Competitor_Activity_Score  136193 non-null  float64
 7   Consumer_Confidence_Index  136193 non-null  float64
 8   Product_Specification_1    136193 non-null  object
 9   Product_Specification_2    136193 non-null  object
 10  Sales_Volume               136193 non-null  int64
dtypes: float64(4), int64(2), object(5)
memory usage: 11.4+ MB

**Data Handling**

In [4]:
original_data["Date"] = pd.to_datetime(original_data["Date"])
original_data = original_data.sort_values("Date")
original_data = original_data.set_index("Date")

**Missing Values**

In [5]:
original_data.isna().sum()

Product_ID                   0
Category                     0
Price                        0
Season                       0
Market_Trend_Index           0
Competitor_Activity_Score    0
Consumer_Confidence_Index    0
Product_Specification_1      0
Product_Specification_2      0
Sales_Volume                 0
dtype: int64

**Encode Categorical Variables (using one-hot encoding**

In [6]:
original_data = pd.get_dummies(
    original_data,
    columns=["Category", "Season", "Product_Specification_1", "Product_Specification_2"],
    drop_first=False
)

In [7]:
original_data.head(4)

,Product_ID,Price,Market_Trend_Index,Competitor_Activity_Score,Consumer_Confidence_Index,Sales_Volume,Category_Accessories,Category_Laptop,Category_Smartphone,Category_Tablet,Season_Fall,Season_Spring,Season_Summer,Season_Winter,Product_Specification_1_Spec_A,Product_Specification_1_Spec_B,Product_Specification_1_Spec_C,Product_Specification_2_High-Resolution,Product_Specification_2_Lightweight,Product_Specification_2_Long-Battery-Life
Date,,,,,,,,,,,,,,,,,,,,
2009-01-01,1103,105.32,-1.859160,0.546694,84.680465,49,False,True,False,False,False,False,False,True,False,False,True,False,False,True
2009-01-01,1022,118.19,-0.541046,-1.198537,49.371590,44,False,False,False,True,False,False,False,True,False,True,False,False,False,True
2009-01-01,1253,63.51,-0.222265,-1.525776,44.538211,87,True,False,False,False,False,False,False,True,False,True,False,False,True,False
2009-01-01,1561,129.27,0.307724,-0.609670,56.835239,84,False,False,True,False,False,False,False,True,True,False,False,True,False,False

In [8]:
original_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 136193 entries, 2009-01-01 to 2020-12-30
Data columns (total 20 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Product_ID                                 136193 non-null  int64
 1   Price                                      136193 non-null  float64
 2   Market_Trend_Index                         136193 non-null  float64
 3   Competitor_Activity_Score                  136193 non-null  float64
 4   Consumer_Confidence_Index                  136193 non-null  float64
 5   Sales_Volume                               136193 non-null  int64
 6   Category_Accessories                       136193 non-null  bool
 7   Category_Laptop                            136193 non-null  bool
 8   Category_Smartphone                        136193 non-null  bool
 9   Category_Tablet                            136193 non-null  bool
 10  Season_Fall                                136193 non-null  bool
 11  Season_Spring                              136193 non-null  bool
 12  Season_Summer                              136193 non-null  bool
 13  Season_Winter                              136193 non-null  bool
 14  Product_Specification_1_Spec_A             136193 non-null  bool
 15  Product_Specification_1_Spec_B             136193 non-null  bool
 16  Product_Specification_1_Spec_C             136193 non-null  bool
 17  Product_Specification_2_High-Resolution    136193 non-null  bool
 18  Product_Specification_2_Lightweight        136193 non-null  bool
 19  Product_Specification_2_Long-Battery-Life  136193 non-null  bool
dtypes: bool(14), float64(4), int64(2)
memory usage: 9.1 MB

Identify Column Groups (for aggregation)

In [9]:
target_col = "Sales_Volume"

numeric_exog = [
    "Price",
    "Market_Trend_Index",
    "Competitor_Activity_Score",
    "Consumer_Confidence_Index"
]

categorical_exog = [
    col for col in original_data.columns
    if col.startswith("Category_")
    or col.startswith("Season_")
    or col.startswith("Product_Specification_2_")
]

**Weekly Dataset** (Operational forecasting / supply planning)

In [10]:
weekly_data = pd.concat([
    original_data[target_col].resample("W").sum(),
    original_data[numeric_exog].resample("W").mean(),
    original_data[categorical_exog].resample("W").mean()
], axis=1)

weekly_data = weekly_data.dropna()

In [11]:
weekly_data.head(4)

,Sales_Volume,Price,Market_Trend_Index,Competitor_Activity_Score,Consumer_Confidence_Index,Category_Accessories,Category_Laptop,Category_Smartphone,Category_Tablet,Season_Fall,Season_Spring,Season_Summer,Season_Winter,Product_Specification_2_High-Resolution,Product_Specification_2_Lightweight,Product_Specification_2_Long-Battery-Life
Date,,,,,,,,,,,,,,,,
2009-01-04,6138,96.498440,-0.080681,-0.130135,70.806253,0.220183,0.238532,0.211009,0.330275,0.0,0.0,0.0,1.0,0.321101,0.366972,0.311927
2009-01-11,10540,99.049439,0.021738,0.033332,69.945363,0.306122,0.224490,0.224490,0.244898,0.0,0.0,0.0,1.0,0.362245,0.326531,0.311224
2009-01-18,8785,101.918538,0.088044,0.112326,69.601186,0.169591,0.298246,0.304094,0.228070,0.0,0.0,0.0,1.0,0.362573,0.263158,0.374269
2009-01-25,12286,101.665992,0.039403,-0.058512,68.744560,0.219409,0.286920,0.240506,0.253165,0.0,0.0,0.0,1.0,0.392405,0.282700,0.324895

In [12]:
weekly_data.columns

Index(['Sales_Volume', 'Price', 'Market_Trend_Index',
       'Competitor_Activity_Score', 'Consumer_Confidence_Index',
       'Category_Accessories', 'Category_Laptop', 'Category_Smartphone',
       'Category_Tablet', 'Season_Fall', 'Season_Spring', 'Season_Summer',
       'Season_Winter', 'Product_Specification_2_High-Resolution',
       'Product_Specification_2_Lightweight',
       'Product_Specification_2_Long-Battery-Life'],
      dtype='object')

In [13]:
weekly_data.shape

(627, 16)

In [14]:
weekly_data.isna().sum().sum()

np.int64(0)

**Monthly Dataset** (Sales planning / budgeting)

In [15]:
monthly_data = pd.concat([
    original_data[target_col].resample("M").sum(),
    original_data[numeric_exog].resample("M").mean(),
    original_data[categorical_exog].resample("M").mean()
], axis=1)

monthly_data = monthly_data.dropna()

In [16]:
monthly_data.head(4)

,Sales_Volume,Price,Market_Trend_Index,Competitor_Activity_Score,Consumer_Confidence_Index,Category_Accessories,Category_Laptop,Category_Smartphone,Category_Tablet,Season_Fall,Season_Spring,Season_Summer,Season_Winter,Product_Specification_2_High-Resolution,Product_Specification_2_Lightweight,Product_Specification_2_Long-Battery-Life
Date,,,,,,,,,,,,,,,,
2009-01-31,48434,100.579176,0.001449,0.002157,69.861168,0.238307,0.252784,0.250557,0.258352,0.0,0.0,0.0,1.0,0.363029,0.309577,0.327394
2009-02-28,56199,104.789057,-0.034940,0.011572,70.052953,0.218377,0.260143,0.244630,0.276850,0.0,0.0,0.0,1.0,0.343675,0.335322,0.321002
2009-03-31,77308,107.628183,-0.017270,0.001256,70.374038,0.238837,0.271028,0.234683,0.255452,0.0,1.0,0.0,0.0,0.331256,0.341641,0.327103
2009-04-30,86614,104.052915,0.042843,-0.025308,71.022053,0.247872,0.230851,0.248936,0.272340,0.0,1.0,0.0,0.0,0.328723,0.347872,0.323404

In [17]:
monthly_data.columns

Index(['Sales_Volume', 'Price', 'Market_Trend_Index',
       'Competitor_Activity_Score', 'Consumer_Confidence_Index',
       'Category_Accessories', 'Category_Laptop', 'Category_Smartphone',
       'Category_Tablet', 'Season_Fall', 'Season_Spring', 'Season_Summer',
       'Season_Winter', 'Product_Specification_2_High-Resolution',
       'Product_Specification_2_Lightweight',
       'Product_Specification_2_Long-Battery-Life'],
      dtype='object')

In [18]:
monthly_data.shape

(144, 16)

In [19]:
monthly_data.isna().sum().sum()

np.int64(0)

**Quarterly Dataset** for Strategic planning

In [20]:
quarterly_data = pd.concat([
    original_data[target_col].resample("Q").sum(),
    original_data[numeric_exog].resample("Q").mean(),
    original_data[categorical_exog].resample("Q").mean()
], axis=1)

quarterly_data = quarterly_data.dropna()

In [21]:
quarterly_data.head(4)

,Sales_Volume,Price,Market_Trend_Index,Competitor_Activity_Score,Consumer_Confidence_Index,Category_Accessories,Category_Laptop,Category_Smartphone,Category_Tablet,Season_Fall,Season_Spring,Season_Summer,Season_Winter,Product_Specification_2_High-Resolution,Product_Specification_2_Lightweight,Product_Specification_2_Long-Battery-Life
Date,,,,,,,,,,,,,,,,
2009-03-31,181941,104.401360,-0.016528,0.004759,70.103706,0.232308,0.261578,0.243053,0.263060,0.000000,0.356799,0.000000,0.643201,0.345684,0.329011,0.325306
2009-06-30,294596,104.972095,0.003268,-0.027601,70.470157,0.254321,0.238448,0.248677,0.258554,0.000000,0.677954,0.322046,0.000000,0.326984,0.349206,0.323810
2009-09-30,382892,108.198351,-0.003026,0.022094,70.014810,0.256871,0.260901,0.234885,0.247343,0.307805,0.000000,0.692195,0.000000,0.327959,0.340418,0.331623
2009-12-31,503679,110.783638,0.009281,-0.009278,69.715520,0.259626,0.243730,0.247262,0.249382,0.675026,0.000000,0.000000,0.324974,0.316496,0.347934,0.335570

In [22]:
quarterly_data.columns

Index(['Sales_Volume', 'Price', 'Market_Trend_Index',
       'Competitor_Activity_Score', 'Consumer_Confidence_Index',
       'Category_Accessories', 'Category_Laptop', 'Category_Smartphone',
       'Category_Tablet', 'Season_Fall', 'Season_Spring', 'Season_Summer',
       'Season_Winter', 'Product_Specification_2_High-Resolution',
       'Product_Specification_2_Lightweight',
       'Product_Specification_2_Long-Battery-Life'],
      dtype='object')

In [23]:
quarterly_data.shape

(48, 16)

In [24]:
quarterly_data.isna().sum().sum()

np.int64(0)

**Annual Dataset** for future forecasting / long-term trends

In [25]:
annual_data = pd.concat([
    original_data[target_col].resample("Y").sum(),
    original_data[numeric_exog].resample("Y").mean(),
    original_data[categorical_exog].resample("Y").mean()
], axis=1)

annual_data = annual_data.dropna()

In [26]:
annual_data.head(4)

,Sales_Volume,Price,Market_Trend_Index,Competitor_Activity_Score,Consumer_Confidence_Index,Category_Accessories,Category_Laptop,Category_Smartphone,Category_Tablet,Season_Fall,Season_Spring,Season_Summer,Season_Winter,Product_Specification_2_High-Resolution,Product_Specification_2_Lightweight,Product_Specification_2_Long-Battery-Life
Date,,,,,,,,,,,,,,,,
2009-12-31,1363108,107.109874,-0.001562,-0.002828,70.076424,0.250946,0.250946,0.243555,0.254552,0.247972,0.260050,0.252569,0.239409,0.329097,0.341806,0.329097
2010-12-31,1412399,106.669378,-0.008910,-0.016157,70.036211,0.250350,0.243605,0.251314,0.254730,0.240802,0.253942,0.260687,0.244569,0.337246,0.332603,0.330151
2011-12-31,1429946,106.789451,0.008273,0.004067,70.066566,0.252277,0.250215,0.250988,0.246520,0.256831,0.247465,0.247723,0.247981,0.329782,0.334422,0.335797
2012-12-31,1391104,106.934485,0.013550,0.003900,70.131437,0.251213,0.247067,0.252889,0.248831,0.259592,0.251654,0.241598,0.247155,0.335450,0.331128,0.333422

In [27]:
annual_data.columns

Index(['Sales_Volume', 'Price', 'Market_Trend_Index',
       'Competitor_Activity_Score', 'Consumer_Confidence_Index',
       'Category_Accessories', 'Category_Laptop', 'Category_Smartphone',
       'Category_Tablet', 'Season_Fall', 'Season_Spring', 'Season_Summer',
       'Season_Winter', 'Product_Specification_2_High-Resolution',
       'Product_Specification_2_Lightweight',
       'Product_Specification_2_Long-Battery-Life'],
      dtype='object')

In [28]:
annual_data.shape

(12, 16)

In [29]:
annual_data.isna().sum().sum()

np.int64(0)

**MODEL DEVELOPMENT**

*Train-Test Split (time-based)*

In [30]:
def train_test_split_ts(data, target_col="Sales_Volume", train_ratio=0.8):
    split = int(len(data) * train_ratio)
    
    y = data[target_col]
    X = data.drop(columns=[target_col])
    
    X_train, X_test = X.iloc[:split], X.iloc[split:]
    y_train, y_test = y.iloc[:split], y.iloc[split:]
    
    return X_train, X_test, y_train, y_test

***SARIMAX MODEL***

*Weekly SARIMAX Forecasting and Evaluation*

In [31]:
#Split data
X_train, X_test, y_train, y_test = train_test_split_ts(weekly_data)

In [32]:
#Train SARIMAX

weekly_sarimax = SARIMAX(
    endog=y_train,
    exog=X_train,
    order=(1, 1, 1),
    seasonal_order=(1, 0, 1, 52),  # yearly seasonality at weekly level
    enforce_stationarity=False,
    enforce_invertibility=False
).fit(disp=False)

print("X_train =", X_train.shape)
print("X_test  =", X_test.shape)

X_train = (501, 15)
X_test  = (126, 15)

In [33]:
# Forecast weekly

weekly_forecast = weekly_sarimax.forecast(
    steps=len(y_test),
    exog=X_test
)

In [34]:
#Evaluate weekly

weekly_mae = mean_absolute_error(y_test, weekly_forecast)
weekly_rmse = np.sqrt(mean_squared_error(y_test, weekly_forecast))
weekly_r2 = r2_score(y_test, weekly_forecast)


print(f"Weekly SARIMAX MAE  = {weekly_mae:.2f}")
print(f"Weekly SARIMAX RMSE = {weekly_rmse:.2f}")
print(f"Weekly SARIMAX R²   = {weekly_r2:.4f}")

Weekly SARIMAX MAE  = 3650.85
Weekly SARIMAX RMSE = 4728.96
Weekly SARIMAX R²   = 0.7498

*Monthly SARIMAX Forecasting and Evaluation*

In [35]:
#Split data

X_train, X_test, y_train, y_test = train_test_split_ts(monthly_data)

In [36]:
#Train SARIMAX

monthly_sarimax = SARIMAX(
    endog=y_train,
    exog=X_train,
    order=(1, 1, 1),
    seasonal_order=(1, 0, 1, 12),
    enforce_stationarity=False,
    enforce_invertibility=False
).fit(disp=False)

In [37]:
#Forecast Monthly

monthly_forecast = monthly_sarimax.forecast(
    steps=len(y_test),
    exog=X_test
)

In [38]:
#Evaluate Monthly

monthly_mae = mean_absolute_error(y_test, monthly_forecast)
monthly_rmse = np.sqrt(mean_squared_error(y_test, monthly_forecast))
monthly_r2 = r2_score(y_test, monthly_forecast)

print(f"Monthly SARIMAX MAE  = {monthly_mae:.2f}")
print(f"Monthly SARIMAX RMSE = {monthly_rmse:.2f}")
print(f"Monthly SARIMAX R²   = {monthly_r2:.4f}")

Monthly SARIMAX MAE  = 11610.67
Monthly SARIMAX RMSE = 15230.52
Monthly SARIMAX R²   = 0.8389

*Quarterly SARIMAX Forecasting and Evaluation*

In [39]:
#Split data

X_train, X_test, y_train, y_test = train_test_split_ts(quarterly_data)

In [40]:
# Train SARIMAX

quarterly_sarimax = SARIMAX(
    endog=y_train,
    exog=X_train,
    order=(1, 1, 1),
    seasonal_order=(1, 0, 0, 4),
    enforce_stationarity=False,
    enforce_invertibility=False
).fit(disp=False)

In [41]:
# Forecast Weekly

quarterly_forecast = quarterly_sarimax.forecast(
    steps=len(y_test),
    exog=X_test
)

In [42]:
quarterly_mae = mean_absolute_error(y_test, quarterly_forecast)
quarterly_rmse = np.sqrt(mean_squared_error(y_test, quarterly_forecast))
quarterly_r2 = r2_score(y_test, quarterly_forecast)

print(f"Quarterly SARIMAX MAE  = {quarterly_mae:.2f}")
print(f"Quarterly SARIMAX RMSE = {quarterly_rmse:.2f}")
print(f"Quarterly SARIMAX R²   = {quarterly_r2:.4f}")

Quarterly SARIMAX MAE  = 31331.14
Quarterly SARIMAX RMSE = 43232.65
Quarterly SARIMAX R²   = 0.8417

*Annual SARIMAX Forecasting and Evaluation*

In [42]:
# Split data

X_train, X_test, y_train, y_test = train_test_split_ts(annual_data)

In [43]:
# Train SARIMAX

annual_sarimax = SARIMAX(
    endog=y_train,
    exog=X_train,
    order=(0, 1, 0),
    seasonal_order=(0, 0, 0, 0)
).fit(disp=False)

In [44]:
# Annual Forecast

annual_forecast = annual_sarimax.forecast(
    steps=len(y_test),
    exog=X_test
)

In [45]:
# Annual Evaluation

annual_mae = mean_absolute_error(y_test, annual_forecast)
annual_rmse = np.sqrt(mean_squared_error(y_test, annual_forecast))
annual_r2 = r2_score(y_test, annual_forecast)

print(f"Annual SARIMAX MAE  = {annual_mae:.2f}")
print(f"Annual SARIMAX RMSE = {annual_rmse:.2f}")
print(f"Annual SARIMAX R²   = {annual_r2:.4f}")

Annual SARIMAX MAE  = 28789.99
Annual SARIMAX RMSE = 38773.07
Annual SARIMAX R²   = -0.1670

**Random Forest Model Evaluation**

In [47]:

def train_random_forest_ts(data, freq_name):
    
    # Split
    X_train, X_test, y_train, y_test = train_test_split_ts(data)

    # Model
    rf_model = RandomForestRegressor(
        n_estimators=300,
        max_depth=None,
        min_samples_leaf=5,
        random_state=42,
        n_jobs=-1
    )

    # Train
    rf_model.fit(X_train, y_train)

    # Predict
    rf_forecast = rf_model.predict(X_test)

    # Metrics
    mae  = mean_absolute_error(y_test, rf_forecast)
    rmse = np.sqrt(mean_squared_error(y_test, rf_forecast))
    r2   = r2_score(y_test, rf_forecast)

    # Output
    print(f"\nRandom Forest Results ({freq_name})")
    print(f"MAE  = {mae:.2f}")
    print(f"RMSE = {rmse:.2f}")
    print(f"R²   = {r2:.4f}")

    return {
        "frequency": freq_name,
        "model": rf_model,
        "mae": mae,
        "rmse": rmse,
        "r2": r2,
        "y_test": y_test,
        "forecast": rf_forecast
    }

*Random Forest Model Result*

In [48]:
rf_weekly    = train_random_forest_ts(weekly_data, "Weekly")
rf_monthly   = train_random_forest_ts(monthly_data, "Monthly")
rf_quarterly = train_random_forest_ts(quarterly_data, "Quarterly")
rf_annual    = train_random_forest_ts(annual_data, "Annual")

Random Forest Results (Weekly)
MAE  = 4361.58
RMSE = 5830.92
R²   = 0.6196

Random Forest Results (Monthly)
MAE  = 11184.51
RMSE = 13995.07
R²   = 0.8640

Random Forest Results (Quarterly)
MAE  = 23795.77
RMSE = 27848.23
R²   = 0.9343

Random Forest Results (Annual)
MAE  = 57837.78
RMSE = 68069.02
R²   = -2.5968

**Prophet Model Evaluation**

In [ ]:
def train_prophet_model(data, freq_name,
                         yearly=True,
                         weekly=False,
                         quarterly=False):

    df = data.reset_index()[[
        "Date",
        "Sales_Volume",
        "Price",
        "Market_Trend_Index",
        "Competitor_Activity_Score",
        "Consumer_Confidence_Index"
    ]]

    df.rename(columns={"Date": "ds", "Sales_Volume": "y"}, inplace=True)

    split = int(len(df) * 0.8)
    train_df = df.iloc[:split]
    test_df  = df.iloc[split:]

    model = Prophet(
        yearly_seasonality=yearly,
        weekly_seasonality=weekly,
        daily_seasonality=False,
        changepoint_prior_scale=0.1
    )

# Regressors
    for reg in [
        "Price",
        "Market_Trend_Index",
        "Competitor_Activity_Score",
        "Consumer_Confidence_Index"
    ]:
        model.add_regressor(reg)

    model.fit(train_df)

# Forecast
    forecast = model.predict(test_df)

    y_true = test_df["y"].values
    y_pred = forecast["yhat"].values

# Evaluation Metrics
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)

    print(f"\nProphet Results ({freq_name})")
    print(f"MAE  = {mae:.2f}")
    print(f"RMSE = {rmse:.2f}")
    print(f"R²   = {r2:.4f}")

    return {
        "frequency": freq_name,
        "mae": mae,
        "rmse": rmse,
        "r2": r2,
        "model": model
    }

***Weekly Prophet***

In [58]:
prophet_weekly = train_prophet_model(
    weekly_data,
    freq_name="Weekly",
    yearly=True,
    weekly=True
)

00:11:38 - cmdstanpy - INFO - Chain [1] start processing
00:11:38 - cmdstanpy - INFO - Chain [1] done processing

Prophet Results (Weekly)
MAE  = 3535.38
RMSE = 4835.53
R²   = 0.7384

***Monthly Prophet***

In [59]:
prophet_monthly = train_prophet_model(
    monthly_data,
    freq_name="Monthly",
    yearly=True
)

00:12:24 - cmdstanpy - INFO - Chain [1] start processing
00:12:24 - cmdstanpy - INFO - Chain [1] done processing

Prophet Results (Monthly)
MAE  = 7941.73
RMSE = 11462.25
R²   = 0.9088

***Quarterly Prophet***

In [60]:
prophet_quarterly = train_prophet_model(
    quarterly_data,
    freq_name="Quarterly",
    yearly=True
)

00:13:41 - cmdstanpy - INFO - Chain [1] start processing
00:13:41 - cmdstanpy - INFO - Chain [1] done processing

Prophet Results (Quarterly)
MAE  = 16019.54
RMSE = 21048.35
R²   = 0.9625

***Annual Prophet***

In [61]:
prophet_annual = train_prophet_model(
    annual_data,
    freq_name="Annual",
    yearly=True
)

00:14:22 - cmdstanpy - INFO - Chain [1] start processing
00:14:22 - cmdstanpy - INFO - Chain [1] done processing

Prophet Results (Annual)
MAE  = 99193.18
RMSE = 135377.00
R²   = -13.2270

**Exponential Smoothing**

In [62]:
def train_ets_model(data, freq_name, seasonal_periods=None):
    """
    ETS model for time series forecasting
    """

    y = data["Sales_Volume"]

    split = int(len(y) * 0.8)
    y_train = y.iloc[:split]
    y_test  = y.iloc[split:]

    model = ExponentialSmoothing(
        y_train,
        trend="add",
        seasonal="add" if seasonal_periods else None,
        seasonal_periods=seasonal_periods
    )

    fitted_model = model.fit()
    forecast = fitted_model.forecast(len(y_test))

    mae = mean_absolute_error(y_test, forecast)
    rmse = np.sqrt(mean_squared_error(y_test, forecast))
    r2 = r2_score(y_test, forecast)

    print(f"\nETS Results ({freq_name})")
    print(f"MAE  = {mae:.2f}")
    print(f"RMSE = {rmse:.2f}")
    print(f"R²   = {r2:.4f}")

    return {
        "frequency": freq_name,
        "model": fitted_model,
        "mae": mae,
        "rmse": rmse,
        "r2": r2
    }

***ETS Weekly (52-week seasonality)***

In [63]:
ets_weekly = train_ets_model(
    weekly_data,
    freq_name="Weekly",
    seasonal_periods=52
)

ETS Results (Weekly)
MAE  = 3622.38
RMSE = 4903.52
R²   = 0.7310

***ETS monthly (12-month seasonality)***

In [64]:
ets_monthly = train_ets_model(
    monthly_data,
    freq_name="Monthly",
    seasonal_periods=12
)

ETS Results (Monthly)
MAE  = 7943.58
RMSE = 11044.24
R²   = 0.9153

***ETS Quarterly (4-quarter seasonality)***

In [65]:
ets_quarterly = train_ets_model(
    quarterly_data,
    freq_name="Quarterly",
    seasonal_periods=4
)

ETS Results (Quarterly)
MAE  = 19852.64
RMSE = 25719.95
R²   = 0.9440

***ETS Annual (No seasonality)***

In [66]:
ets_annual = train_ets_model(
    annual_data,
    freq_name="Annual",
    seasonal_periods=None
)

ETS Results (Annual)
MAE  = 64428.65
RMSE = 73695.51
R²   = -3.2160